### PR TITLE
vms

### PR DESCRIPTION
**Pull request by SandiaScalpel**

### CODE REVIEW

**Comment by jordanhubbard** [comment]
I know this was closed, but JFYI...  I'm not sure Microsoft would look kindly upon the notion of a preinstalled Windows template.  That's why we never provided one ourselves. :)

**Comment by SandiaScalpel** [comment]
Hi, I was trying to figure out how to restore a Windows vm that I had made
a compressed backup image of the disk device for. Having difficulties...

If I have hd.img which was made from dd of the vm disk device, how to I
rebuild the vn from that?

Any help appreciated...

Sean

**Comment by jordanhubbard** [comment]
You use the template to create new VMs, adding the URL to your vm template repository in VM -> Settings so that you'll see your templates.

**Comment by SandiaScalpel** [comment]
Thanks Jordan,

I haven't been able to figure out how to do the whole commit / push stuff
on github... stared at it for hours. Doing something wrong I'm sure, but
it's OK - I don't need to figure this out... I'm not in IT. I did figure
out how to re-create my windows VM from my boot disk backup image. I'll
probably post the steps in the forums. Actually quite simple.

Sean

**Pull request closed without merging**
